version: "3.9"

services:
  db:
    image: postgres:15
    container_name: erp_db
    restart: always
    environment:
      POSTGRES_DB: erpmini
      POSTGRES_USER: ${POSTGRES_USER:-erpuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me_strong_password}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bamboo -d erpmini"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - erp_network

  redis:
    image: redis:7-alpine
    container_name: erp_redis
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-change_me_redis_password}
    volumes:
      - redisdata:/data
    networks:
      - erp_network

  web:
    build: .
    container_name: erp_web
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-erpuser}:${POSTGRES_PASSWORD:-change_me_strong_password}@db:5432/erpmini
      APP_MODE: ${APP_MODE:-dev}
      FLASK_ENV: ${FLASK_ENV:-development}
      REDIS_URL: redis://:${REDIS_PASSWORD:-change_me_redis_password}@redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app # 👉 DEV dùng
    command: >
      sh -c "python wait_for_db.py &&
             if [ \"$APP_MODE\" = 'dev' ];
             then python run.py;
             else gunicorn -c gunicorn.conf.py wsgi:app;
             fi"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/auth/login >/dev/null || curl -fsS http://localhost:5000/auth/login >/dev/null"]
      interval: 20s
      timeout: 5s
      retries: 10
    networks:
      - erp_network

  nginx:
    image: nginx:latest
    container_name: erp_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - erp_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: erp_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-change_me_pgadmin_password}
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - erp_network

volumes:
  pgdata:
  pgadmin_data:
  redisdata:

networks:
  erp_network:
    driver: bridge
