"""add payment_method to online_orders

Revision ID: 51c6e6a1fb16
Revises: 0010stocktaking
Create Date: 2026-07-16 18:42:41.484557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c6e6a1fb16'
down_revision = '0010stocktaking'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('account_charts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ac_code_active'), postgresql_where='(is_active = true)')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_session_status'))

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(precision=18, scale=0),
               type_=sa.Numeric(precision=18, scale=3),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_constraint(batch_op.f('cart_items_cart_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cart', ['cart_id'], ['id'])
        batch_op.drop_column('retail_price')

    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.create_index('ix_debts_partner', ['partner_type', 'partner_id'], unique=False)
        batch_op.create_index('ix_debts_status', ['status'], unique=False)

    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.create_index('ix_inv_hist_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_inv_hist_product_wh', ['product_id', 'warehouse_id'], unique=False)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_je_date_status'), postgresql_where="((status)::text = 'posted'::text)")
        batch_op.drop_index(batch_op.f('idx_je_reference'))
        batch_op.create_index('ix_je_date', ['date'], unique=False)
        batch_op.create_index('ix_je_reference', ['reference_type', 'reference_id'], unique=False)

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_jl_account'))
        batch_op.drop_index(batch_op.f('idx_jl_partner'), postgresql_where='(partner_id IS NOT NULL)')

    with op.batch_alter_table('menu_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_menu_roles_role'))

    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.alter_column('roles',
               existing_type=sa.VARCHAR(length=200),
               comment='Quyền truy cập (CSV, legacy)',
               existing_comment='Quyền truy cập (CSV)',
               existing_nullable=True)

    with op.batch_alter_table('online_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('ix_online_orders_created_at'))
        batch_op.drop_index(batch_op.f('ix_online_orders_sync_status'))

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_product_images_product'))
        batch_op.drop_index(batch_op.f('ux_product_images_main'), postgresql_where='(is_main = true)')
        batch_op.create_index('ix_product_images_product_id', ['product_id'], unique=False)

    with op.batch_alter_table('product_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_listings_published'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('retail_price',
               existing_type=sa.NUMERIC(precision=18, scale=0),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
        batch_op.create_index('ix_products_category_id', ['category_id'], unique=False)
        batch_op.create_index('ix_products_name', ['name'], unique=False)
        batch_op.drop_column('contact_for_price')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('quotation_items_quotation_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'quotations', ['quotation_id'], ['id'])

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index('ix_quotations_customer_date', ['customer_id', 'date'], unique=False)
        batch_op.create_index('ix_quotations_date', ['date'], unique=False)
        batch_op.create_index('ix_quotations_status', ['status'], unique=False)

    with op.batch_alter_table('stock_in_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stock_ins_unit'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'units', ['unit_id'], ['id'])

    with op.batch_alter_table('stock_ins', schema=None) as batch_op:
        batch_op.create_index('ix_stock_ins_date', ['date'], unique=False)
        batch_op.create_index('ix_stock_ins_status', ['status'], unique=False)
        batch_op.create_index('ix_stock_ins_supplier_date', ['supplier_id', 'date'], unique=False)
        batch_op.create_index('ix_stock_ins_warehouse_date', ['warehouse_id', 'date'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_stock_ins_unit'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'units', ['unit_id'], ['id'])

    with op.batch_alter_table('stock_out_items', schema=None) as batch_op:
        batch_op.alter_column('box_note',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_stock_ins_unit'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'units', ['unit_id'], ['id'])

    with op.batch_alter_table('stock_outs', schema=None) as batch_op:
        batch_op.create_index('ix_stock_outs_customer_date', ['customer_id', 'date'], unique=False)
        batch_op.create_index('ix_stock_outs_date', ['date'], unique=False)
        batch_op.create_index('ix_stock_outs_status', ['status'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_stock_ins_unit'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'units', ['unit_id'], ['id'])

    with op.batch_alter_table('stocktaking_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocktaking_items_session'))

    with op.batch_alter_table('stocktakings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocktakings_warehouse_date'))

    with op.batch_alter_table('unit_conversions', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('from_unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('to_unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('unit_conversions_product_id_from_unit_id_to_unit_id_key'), type_='unique')
        batch_op.create_unique_constraint('uq_unit_conv', ['product_id', 'from_unit_id', 'to_unit_id'])

    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_permissions_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_permissions_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('unit_conversions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_unit_conv', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unit_conversions_product_id_from_unit_id_to_unit_id_key'), ['product_id', 'from_unit_id', 'to_unit_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('to_unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('from_unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('stocktakings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocktakings_warehouse_date'), ['warehouse_id', 'count_date'], unique=False)

    with op.batch_alter_table('stocktaking_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocktaking_items_session'), ['stocktaking_id'], unique=False)

    with op.batch_alter_table('stock_outs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_stock_ins_unit'), 'units', ['unit_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index('ix_stock_outs_status')
        batch_op.drop_index('ix_stock_outs_date')
        batch_op.drop_index('ix_stock_outs_customer_date')

    with op.batch_alter_table('stock_out_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_stock_ins_unit'), 'units', ['unit_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('box_note',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('stock_ins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_stock_ins_unit'), 'units', ['unit_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index('ix_stock_ins_warehouse_date')
        batch_op.drop_index('ix_stock_ins_supplier_date')
        batch_op.drop_index('ix_stock_ins_status')
        batch_op.drop_index('ix_stock_ins_date')

    with op.batch_alter_table('stock_in_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_stock_ins_unit'), 'units', ['unit_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index('ix_quotations_status')
        batch_op.drop_index('ix_quotations_date')
        batch_op.drop_index('ix_quotations_customer_date')

    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('quotation_items_quotation_id_fkey'), 'quotations', ['quotation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contact_for_price', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.drop_index('ix_products_name')
        batch_op.drop_index('ix_products_category_id')
        batch_op.alter_column('retail_price',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=18, scale=0),
               existing_nullable=True)

    with op.batch_alter_table('product_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_listings_published'), ['is_published'], unique=False)

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index('ix_product_images_product_id')
        batch_op.create_index(batch_op.f('ux_product_images_main'), ['product_id'], unique=True, postgresql_where='(is_main = true)')
        batch_op.create_index(batch_op.f('idx_product_images_product'), ['product_id'], unique=False)

    with op.batch_alter_table('online_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_online_orders_sync_status'), ['sync_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_online_orders_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.alter_column('roles',
               existing_type=sa.VARCHAR(length=200),
               comment='Quyền truy cập (CSV)',
               existing_comment='Quyền truy cập (CSV, legacy)',
               existing_nullable=True)

    with op.batch_alter_table('menu_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_menu_roles_role'), ['role'], unique=False)

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_jl_partner'), ['partner_id'], unique=False, postgresql_where='(partner_id IS NOT NULL)')
        batch_op.create_index(batch_op.f('idx_jl_account'), ['account_id'], unique=False)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_je_reference')
        batch_op.drop_index('ix_je_date')
        batch_op.create_index(batch_op.f('idx_je_reference'), ['reference_type', 'reference_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_je_date_status'), ['date', 'status'], unique=False, postgresql_where="((status)::text = 'posted'::text)")

    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.drop_index('ix_inv_hist_product_wh')
        batch_op.drop_index('ix_inv_hist_created_at')

    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_index('ix_debts_status')
        batch_op.drop_index('ix_debts_partner')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retail_price', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cart_items_cart_id_fkey'), 'cart', ['cart_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=18, scale=3),
               type_=sa.NUMERIC(precision=18, scale=0),
               existing_nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_session_status'), ['session_id', 'status'], unique=False)

    with op.batch_alter_table('account_charts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ac_code_active'), ['code'], unique=False, postgresql_where='(is_active = true)')

    op.drop_table('erp_users')
    # ### end Alembic commands ###
